name: budpay_inline_flutter
description: "Budpay's flutter plugin for making payments via BudPay inline Payment Gateway. Supports Android and iOS platforms"
version: 0.0.2
homepage: https://github.com/okeybudpay/budpay_inline_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  webview_flutter: ^4.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.budpay_inline_flutter
        pluginClass: BudpayInlineFlutterPlugin
      ios:
        pluginClass: BudpayInlineFlutterPlugin
